<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>    
  </PropertyGroup>

	<PropertyGroup>
		<ErrorOnDuplicatePublishOutputFiles>false</ErrorOnDuplicatePublishOutputFiles>
	</PropertyGroup>

	<ItemGroup>
  <None Remove="ViewYourFunding.Core.csproj.transform" />
  </ItemGroup>

  <ItemGroup>
  <PackageReference Include="Pds.Core.CodeAnalysis.StyleCop" Version="2.0.0" />
  </ItemGroup>

</Project>
