---
# yamllint disable rule:line-length
trigger:
  batch: true
  branches:
    include:
      - '*'

pr: none

pool:
  vmImage: ubuntu-latest

name: $(Build.BuildId)

variables:
  buildConfiguration: release
  #.NET SDK version number
  dotnetVersion: '8.0'
  #PDS custom NuGet feed id
  nugetFeed: 9fd46a3f-eada-41dc-86e9-36332aeb8ef1/ecd5af68-0566-42db-8cd7-e71176254aa2
  #Path of project to be published
  publishProjectPath: ViewYourFunding.Web/PDS.ViewYourFunding.Web/PDS.ViewYourFunding.Web.csproj
  #Docker variables
  dockerRegistryServiceConnectionDev: PDS-DEV-ACR
  dockerRegistryServiceConnectionPreProd: PDS-OAT-ACR
  dockerRegistryServiceConnectionProd: PDS-Release-ACR
  imageRepository: myesf/pds-app-fundingui
  dockerfilePath: ViewYourFunding.Web/PDS.ViewYourFunding.Web/Dockerfile
  tag: $(Build.BuildId)
  patToken: $(System.AccessToken)

stages:
#Stage 1 - Audit stage: This stage checks project dependencies for security vulnerabilities
- stage: Audit
  displayName: Run audit activities
  condition: always()
  jobs:
  #Job 1 - Audit: This job checks project dependencies for secuirty vulnerabilites using default dotnet command 
  - job: Audit
    displayName: Audit project dependencies for security vulnerabilites
    steps:
    # Step 1 - Set up .NET SDK
    - task: UseDotNet@2
      displayName: Set up .NET SDK (version $(dotnetVersion))
      inputs:
        packageType: sdk
        version: $(dotnetVersion).x
    #Step 2 - Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: Restore .NET project dependencies (NuGet)
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: select
        vstsFeed: $(nugetFeed)
    #Step 3 - Check for security vulnerabilities within project dependencies
    - task: Bash@3
      displayName: Scan for vulnerable NuGet packages
      inputs:
        targetType: inline
        script: |
          # Run dotnet command to check for vulnerable packages, including transitive dependencies
          dotnet list package --vulnerable --include-transitive 2>&1 | tee build.log
          echo 'Analyse dotnet list package command log output...'
          if grep -q -i 'critical\|high' build.log; then
              echo 'Must fix security vulnerabilities found on the log output.'
              exit 1      # Fails the job if critical or high vulnerabilities are found
          else
              echo 'No critical or high severity vulnerabilities found.'
              exit 0      # Passes the job if no critical/high vulnerabilities are found
          fi

  #Stage 2 - Test stage: This stage runs the project unit tests
- stage: Test
  displayName: Run unit tests
  dependsOn: Audit
  condition: succeeded()
  jobs:
  #Job 1 - Unit: Runs unit tests.
  - job: Unit
    displayName: Run unit tests
    dependsOn: []
    steps:
    # Step 1 - Download the Aspose License
    - task: DownloadSecureFile@1
      name: downloadAsposeLicense
      displayName: 'Download Aspose License'
      inputs:
        secureFile: AsposeTotalLicense
    # Step 2 - Copy the Aspose License to the destination
    - task: PowerShell@2
      name: copyAsposeLicense
      displayName: 'Copy Aspose license to source'
      inputs:
        targetType: inline
        script: |
            $sourceDestination = "$(System.DefaultWorkingDirectory)\ViewYourFunding.Web\PDS.ViewYourFunding.Services\Resources\"
            Write-Host "Copying aspose license from $(downloadAsposeLicense.secureFilePath) to target '$sourceDestination\Aspose.Total.lic'"

            if(-not (Test-Path -Path "$sourceDestination")) {
              New-Item -Type Directory -Path "$sourceDestination"
            }

            Copy-Item -Path "$(downloadAsposeLicense.secureFilePath)" -Destination "$sourceDestination\Aspose.Total.lic"
            Write-Host "File copied!"
    # Step 3 - Set up .NET SDK
    - task: UseDotNet@2
      displayName: Set up .NET SDK (version $(dotnetVersion))
      inputs:
        packageType: sdk
        version: $(dotnetVersion).x
    #Step 4 - Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: Restore .NET project dependencies (NuGet)
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: select
        vstsFeed: $(nugetFeed)
        verbosityRestore: Normal
    # Step 5 - Build the project
    - task: DotNetCoreCLI@2
      displayName: Build project
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: --configuration $(buildConfiguration) --no-restore
    # Step 6 - Run unit tests and filter by category
    - task: DotNetCoreCLI@2
      displayName: Run unit tests
      inputs:
        command: test
        projects: '**/*[Tt]ests/*.csproj'
        arguments: --configuration $(buildConfiguration) --no-build --collect "Code coverage" --filter TestCategory=Unit
        testRunTitle: $(Build.Repository.Name)-Unit-$(Build.BuildId)

#Stage 3 - Publish stage: This stage publishes the Docker Image and build artifact to be deployed in the release pipelines
- stage: Publish
  displayName: Publish Docker image and build artifact
  dependsOn: Test
  condition: and(succeeded(), or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix')))
  jobs:
  # Job 1 - Build and Push to Development ACR
  - job: DockerBuildDev
    displayName: Build and push Docker image for Development
    condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/main'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix'))
    steps:
    # Step 1 - Download the Aspose License
    - task: DownloadSecureFile@1
      name: downloadAsposeLicense
      displayName: 'Download Aspose License'
      inputs:
        secureFile: AsposeTotalLicense
    # Step 2 - Copy the Aspose License to the destination
    - task: PowerShell@2
      name: copyAsposeLicense
      displayName: 'Copy Aspose license to source'
      inputs:
        targetType: inline
        script: |
            $sourceDestination = "$(System.DefaultWorkingDirectory)\ViewYourFunding.Web\PDS.ViewYourFunding.Services\Resources\"
            Write-Host "Copying aspose license from $(downloadAsposeLicense.secureFilePath) to target '$sourceDestination\Aspose.Total.lic'"

            if(-not (Test-Path -Path "$sourceDestination")) {
              New-Item -Type Directory -Path "$sourceDestination"
            }

            Copy-Item -Path "$(downloadAsposeLicense.secureFilePath)" -Destination "$sourceDestination\Aspose.Total.lic"
            Write-Host "File copied!"
    # Step 3: Build the Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionDev)
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)/ViewYourFunding.Web
        tags: |
          latest
          $(tag)
        arguments: |
          --build-arg PDS_FEED_PAT=$(patToken)
    # Step 4: Push the Docker image to the Development container registry
    - task: Docker@2
      displayName: Push Docker image to Development container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionDev)
        tags: |
          latest
          $(tag)
  # Job 2 - Build and Push to Pre-production and Production ACR
  - job: DockerBuildPreProdProd
    displayName: Build and push Docker Image for Pre-production and Production
    condition: startsWith(variables['build.sourceBranch'], 'refs/heads/release')
    steps:
    # Step 1 - Download the Aspose License
    - task: DownloadSecureFile@1
      name: downloadAsposeLicense
      displayName: 'Download Aspose License'
      inputs:
        secureFile: AsposeTotalLicense
    # Step 2 - Copy the Aspose License to the destination
    - task: PowerShell@2
      name: copyAsposeLicense
      displayName: 'Copy Aspose license to source'
      inputs:
        targetType: inline
        script: |
            $sourceDestination = "$(System.DefaultWorkingDirectory)\ViewYourFunding.Web\PDS.ViewYourFunding.Services\Resources\"
            Write-Host "Copying aspose license from $(downloadAsposeLicense.secureFilePath) to target '$sourceDestination\Aspose.Total.lic'"

            if(-not (Test-Path -Path "$sourceDestination")) {
              New-Item -Type Directory -Path "$sourceDestination"
            }

            Copy-Item -Path "$(downloadAsposeLicense.secureFilePath)" -Destination "$sourceDestination\Aspose.Total.lic"
            Write-Host "File copied!"
    # Step 3: Build the Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionPreProd)
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)/ViewYourFunding.Web
        tags: |
          latest-rc
          $(tag)-rc
        arguments:
          --build-arg PDS_FEED_PAT=$(patToken)
    # Step 4: Push the Docker image to the Pre-prod container registry
    - task: Docker@2
      displayName: Push Docker image to Pre-prod container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionPreProd)
        tags: |
          latest-rc
          $(tag)-rc
    # Step 5: Build the Docker image
    - task: Docker@2
      displayName: Build Docker image
      inputs:
        command: build
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionProd)
        dockerfile: $(dockerfilePath)
        buildContext: $(Build.SourcesDirectory)/ViewYourFunding.Web
        tags: |
          latest-rc
          $(tag)-rc
        arguments:
          --build-arg PDS_FEED_PAT=$(patToken)
    # Step 6: Push the Docker image to the Prod container registry
    - task: Docker@2
      displayName: Push Docker image to Prod container registry
      inputs:
        command: push
        repository: $(imageRepository)
        containerRegistry: $(dockerRegistryServiceConnectionProd)
        tags: |
          latest-rc
          $(tag)-rc
  # Job 3 - Publish: This job publishes the build artifact from the project
  - job: PublishArtifact
    displayName: Publish build artifact
    steps:
    # Step 1 - Download the Aspose License
    - task: DownloadSecureFile@1
      name: downloadAsposeLicense
      displayName: 'Download Aspose License'
      inputs:
        secureFile: AsposeTotalLicense
    # Step 2 - Copy the Aspose License to the destination
    - task: PowerShell@2
      name: copyAsposeLicense
      displayName: 'Copy Aspose license to source'
      inputs:
        targetType: inline
        script: |
            $sourceDestination = "$(System.DefaultWorkingDirectory)\ViewYourFunding.Web\PDS.ViewYourFunding.Services\Resources\"
            Write-Host "Copying aspose license from $(downloadAsposeLicense.secureFilePath) to target '$sourceDestination\Aspose.Total.lic'"

            if(-not (Test-Path -Path "$sourceDestination")) {
              New-Item -Type Directory -Path "$sourceDestination"
            }

            Copy-Item -Path "$(downloadAsposeLicense.secureFilePath)" -Destination "$sourceDestination\Aspose.Total.lic"
            Write-Host "File copied!"
    # Step 3 - Set up .NET SDK
    - task: UseDotNet@2
      displayName: Set up .NET SDK (version $(dotnetVersion))
      inputs:
        packageType: sdk
        version: $(dotnetVersion).x
    #Step 4 - Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: Restore .NET project dependencies (NuGet)
      inputs:
        command: restore
        projects: '**/*.csproj'
        feedsToUse: select
        vstsFeed: $(nugetFeed)
        verbosityRestore: Normal
    # Step 5 - Build the project
    - task: DotNetCoreCLI@2
      displayName: Build project
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: --configuration $(buildConfiguration) --no-restore
    #Step 6 - Publish project
    - task: DotNetCoreCLI@2
      displayName: Publish project
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: true
        projects: $(publishProjectPath)
        arguments: --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build
    #Step 7 - Publish tests for release pipelines
    - task: DotNetCoreCLI@2
      displayName: Publish Tests
      inputs:
        command: publish
        publishWebProjects: false
        zipAfterPublish: false
        projects: '**/*Tests/*.csproj'
        arguments: --configuration $(buildConfiguration) --output $(build.artifactstagingdirectory)/publish --no-restore --no-build
    #Step 8 - Copy published project to artifact directory
    - task: CopyFiles@2
      displayName: 'Copy files to: $(build.artifactstagingdirectory)'
      inputs:
        contents: |
          azure/**
        targetFolder: $(build.artifactstagingdirectory)/publish
    #Step 9 - Publish build artifact
    - task: PublishBuildArtifacts@1
      displayName: Publish build artifact
      inputs:
        pathtoPublish: $(build.artifactstagingdirectory)/publish