// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PDS.ViewYourFunding.Repositories.Implementations;

namespace PDS.ViewYourFunding.Repositories.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20220218122054_UpdatePNAShowOnProviderLoggedInView")]
    partial class UpdatePNAShowOnProviderLoggedInView
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.FundingStream", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FundingStreamBusinessAllocationName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundingStreamCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FundingStreamCodePubliclyKnown")
                        .HasColumnType("bit");

                    b.Property<string>("FundingStreamName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundingStreamNameWithinSentence")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HistoryIndependentOfPublications")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<bool>("RelevantForNational")
                        .HasColumnType("bit");

                    b.Property<bool>("RelevantForOrganisations_LoggedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("RelevantForOrganisations_Public")
                        .HasColumnType("bit");

                    b.Property<bool>("RelevantForProviders_LoggedIn")
                        .HasColumnType("bit");

                    b.Property<bool>("RelevantForProviders_Public")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("FundingStreams");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.GlobalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EditType")
                        .HasColumnType("int");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ReadOnly")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GlobalSettings");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.NextPayment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FundingPeriodCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FundingStreamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<DateTime>("NextPaymentDate")
                        .HasColumnType("Date");

                    b.Property<int>("NextPaymentTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundingStreamId");

                    b.HasIndex("NextPaymentTypeId");

                    b.ToTable("NextPayments");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.NextPaymentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FundingStreamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)")
                        .HasMaxLength(128);

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("FundingStreamId");

                    b.ToTable("NextPaymentTypes");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.Publication", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CutOffDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FundingPeriodCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FundingStreamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SpreadsheetModelVersion")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("UIModelVersion")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FundingStreamId");

                    b.ToTable("Publications");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.PublicationLayout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundingViewScope")
                        .HasColumnType("int");

                    b.Property<int>("FundingViewType")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LayoutId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PublicationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PublicationId");

                    b.ToTable("PublicationLayouts");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SettingName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ValueDataType")
                        .HasColumnType("int");

                    b.Property<bool>("ValuesAreEditable")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.SettingValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FundingStreamId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastUpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SettingId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FundingStreamId");

                    b.HasIndex("SettingId");

                    b.ToTable("SettingValues");
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.NextPayment", b =>
                {
                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.FundingStream", "FundingStream")
                        .WithMany("NextPayments")
                        .HasForeignKey("FundingStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.NextPaymentType", "NextPaymentType")
                        .WithMany("NextPayments")
                        .HasForeignKey("NextPaymentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.NextPaymentType", b =>
                {
                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.FundingStream", "FundingStream")
                        .WithMany("NextPaymentTypes")
                        .HasForeignKey("FundingStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.Publication", b =>
                {
                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.FundingStream", "FundingStream")
                        .WithMany("Publications")
                        .HasForeignKey("FundingStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.PublicationLayout", b =>
                {
                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.Publication", null)
                        .WithMany("PublicationLayouts")
                        .HasForeignKey("PublicationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PDS.ViewYourFunding.Repositories.DataModels.SettingValue", b =>
                {
                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.FundingStream", "FundingStream")
                        .WithMany("SettingValues")
                        .HasForeignKey("FundingStreamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PDS.ViewYourFunding.Repositories.DataModels.Setting", "Setting")
                        .WithMany("SettingValues")
                        .HasForeignKey("SettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
